### ISSUE TITLE
no mention of bash completion requirement

### ISSUE THREAD

**Issue by sigmonsays** [driv/upto#8]
$ upto _tab key_ shows "bash: _init_completion: command not found"

Not mentioned in the documentation. Also this seems like a needlessly large dependency as well since I am not in favor of the bash completion package. Is there an alternative to full on bash completion?

**Comment by driv** [comment]
Maybe split it and let the user decide if they also want to "install" completion?
@grivet what do you think?

**Comment by grivet** [comment]
I made a simple fix to check for the declaration of _init_completion before using it.

The main problem is thus that it enables the completion only for users using bash_completion. However, it seems logical that one follows the other. See if it is acceptable.

(I will do a pull request with it)

**Comment by sigmonsays** [comment]
works for me, not sure who you were asking.
